#!/bin/sh

set -e

# Parse keymap
keymap -c img/config.yaml parse -z config/mriya.keymap >img/mriya.yaml

# Draw keymap
keymap -c img/config.yaml draw -j config/mriya.json img/mriya.yaml >img/mriya.svg
